//created on: Jun 20, 2018
package com.sample

//list any import classes here.

import com.sbnz.sbnzproject.model.*;
import java.util.*;

rule "Broj simptoma za svaku bolest"
	no-loop
	lock-on-active true
	when
		$d : PossibleDisease( $dsymptoms: disease.getSymptoms() )
		accumulate(
			$s : PossibleSymptom (
				symptom memberOf $dsymptoms
			);
            $count:count($s)
		)
	then
		modify($d) {setNumSymptoms($count);}
end