insert into user(id, username, password, name, last_name, role) value (1, "admin", "$2a$08$lDnHPz7eUkSi6ao14Twuau08mzhWrL4kyZGGU5xfiGALO/Vxd5DOi", "admin", "admin", "ADMIN")
insert into user(id, username, password, name, last_name, role) value (2, "doctor", "$2a$08$lDnHPz7eUkSi6ao14Twuau08mzhWrL4kyZGGU5xfiGALO/Vxd5DOi", "doctor", "doctor", "DOCTOR")
insert into symptom(id, name, symptom_type) value (1, "curenje iz nosa", "GENERAL")
insert into symptom(id, name, symptom_type) value (2, "bol u grlu", "GENERAL")
insert into symptom(id, name, symptom_type) value (3, "glavobolja", "GENERAL")
insert into symptom(id, name, symptom_type) value (4, "kijanje", "GENERAL")
insert into symptom(id, name, symptom_type) value (5, "kasalj", "GENERAL")
insert into symptom(id, name, symptom_type) value (6, "temperatura veca od 38", "GENERAL")
insert into symptom(id, name, symptom_type) value (7, "drhtavica", "GENERAL")
insert into symptom(id, name, symptom_type) value (8, "bol koji se siri do usiju", "GENERAL")
insert into symptom(id, name, symptom_type) value (9, "temperatura od 40 do 41", "GENERAL")
insert into symptom(id, name, symptom_type) value (10, "gubitak apetita", "GENERAL")
insert into symptom(id, name, symptom_type) value (11, "umor", "GENERAL")
insert into symptom(id, name, symptom_type) value (12, "zuti sekret iz nosa", "GENERAL")
insert into symptom(id, name, symptom_type) value (13, "oticanje oko ociju", "GENERAL")
insert into symptom(id, name, symptom_type) value (14, "cesto uriniranje", "GENERAL")
insert into symptom(id, name, symptom_type) value (15, "gubitak tjelesne tezine", "GENERAL")
insert into symptom(id, name, symptom_type) value (16, "mucnina i povracanje", "GENERAL")
insert into symptom(id, name, symptom_type) value (17, "zamor", "GENERAL")
insert into symptom(id, name, symptom_type) value (18, "nocturia", "GENERAL")
insert into symptom(id, name, symptom_type) value (19, "otoci nogu i zglobova", "GENERAL")
insert into symptom(id, name, symptom_type) value (20, "gusenje", "GENERAL")
insert into symptom(id, name, symptom_type) value (21, "bol u grudima", "GENERAL")
insert into symptom(id, name, symptom_type) value (22, "dijareja", "GENERAL")
insert into patient(id, name, last_name, email) value (1, "niki", "radi", "rnikolina")
insert into patient(id, name, last_name, email) value (2, "saki", "rad", "sandrolina")
insert into patient(id, name, last_name, email) value (3, "uki", "ukic", "jocko")